export const healthyWeightRangesByBreed = {
  dog: {
    // Breed-specific healthy weight ranges for dogs
    "labrador retriever": { min: 55, max: 80 },
    "german shepherd": { min: 50, max: 90 },
    "golden retriever": { min: 55, max: 75 },
    "french bulldog": { min: 16, max: 28 },
    "bulldog": { min: 40, max: 50 },
    "poodle (standard)": { min: 40, max: 70 },
    "poodle (miniature)": { min: 10, max: 15 },
    "poodle (toy)": { min: 4, max: 6 },
    "beagle": { min: 20, max: 30 },
    "rottweiler": { min: 80, max: 135 },
    "yorkshire terrier": { min: 4, max: 7 },
    "boxer": { min: 55, max: 70 },
    "dachshund (standard)": { min: 16, max: 32 },
    "dachshund (miniature)": { min: 8, max: 11 },
    "siberian husky": { min: 35, max: 60 },
    "doberman pinscher": { min: 60, max: 100 },
    "great dane": { min: 110, max: 175 },
    "shih tzu": { min: 9, max: 16 },
    "pomeranian": { min: 3, max: 7 },
    "chihuahua": { min: 3, max: 6 },
    "border collie": { min: 30, max: 55 },
    "australian shepherd": { min: 40, max: 65 },
    "boston terrier": { min: 12, max: 25 },
    "maltese": { min: 4, max: 7 },
    "cocker spaniel": { min: 20, max: 30 },
    "basset hound": { min: 40, max: 65 },
    "pug": { min: 14, max: 18 },
    "staffordshire bull terrier": { min: 24, max: 38 },
    "akita": { min: 70, max: 130 },
    "newfoundland": { min: 100, max: 150 },
    "bernese mountain dog": { min: 70, max: 115 },
    "cavalier king charles spaniel": { min: 13, max: 18 },
    "weimaraner": { min: 55, max: 90 },
    "whippet": { min: 25, max: 40 }
  },
  cat: {
    // Breed-specific healthy weight ranges for cats
    "american curl": { min: 7, max: 12 },
    "maine coon": { min: 10, max: 25 },
    "persian": { min: 7, max: 12 },
    "siamese": { min: 6, max: 14 },
    "domestic shorthair": { min: 8, max: 15 },
    "ragdoll": { min: 10, max: 20 },
    "sphynx": { min: 6, max: 12 },
    "british shorthair": { min: 9, max: 18 },
    "scottish fold": { min: 6, max: 13 },
    "bengal": { min: 8, max: 15 },
    "norwegian forest cat": { min: 9, max: 16 },
    "abyssinian": { min: 6, max: 10 },
    "oriental shorthair": { min: 6, max: 12 },
    "burmese": { min: 6, max: 12 },
    "manx": { min: 8, max: 12 },
    "turkish angora": { min: 5, max: 10 },
    "exotic shorthair": { min: 7, max: 14 },
    "korat": { min: 6, max: 10 }
  },
  fallback: {
    dog: {
      small: { min: 5, max: 22 },
      medium: { min: 23, max: 55 },
      large: { min: 56, max: 100 },
      giant: { min: 101, max: 200 }
    },
    cat: { min: 7, max: 12 }
  }
};

// Breed → size category (for dogs only)
export const dogBreedSizeCategory = {
  "labrador retriever": "large",
  "german shepherd": "large",
  "golden retriever": "large",
  "french bulldog": "small",
  "bulldog": "medium",
  "poodle (standard)": "large",
  "poodle (miniature)": "small",
  "poodle (toy)": "small",
  "beagle": "small",
  "rottweiler": "large",
  "yorkshire terrier": "small",
  "boxer": "large",
  "dachshund (standard)": "small",
  "dachshund (miniature)": "small",
  "siberian husky": "medium",
  "doberman pinscher": "large",
  "great dane": "giant",
  "shih tzu": "small",
  "pomeranian": "small",
  "chihuahua": "small",
  "border collie": "medium",
  "australian shepherd": "medium",
  "boston terrier": "small",
  "maltese": "small",
  "cocker spaniel": "medium",
  "basset hound": "medium",
  "pug": "small",
  "staffordshire bull terrier": "medium",
  "akita": "large",
  "newfoundland": "giant",
  "bernese mountain dog": "large",
  "cavalier king charles spaniel": "small",
  "weimaraner": "large",
  "whippet": "medium"
};
